### ISSUE TITLE
Actualizar Zona Counter

### ISSUE THREAD

**Issue by pacoelayudante** [pacoelayudante/teamGuazu#1]
La Zona Counter tiene un comportamiento diseñado que no está implementado.
La forma que esta construida técnicamente la Zona Counter es bastante chota.

**Comment by RojoMcGil** [comment]
Las colas de gatitos. 
shake de camara

**Comment by pacoelayudante** [comment]
nabo, hay un boton que dice "New Issue" en verde rabioso

2015-05-19 15:50 GMT-03:00 RojoMcGil <notifications@github.com>:
